baseURL: "mdsayeb7.github.io"
title: Sayfullah Sayeb
pagination.pagerSize: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Sayfullah Sayeb
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: true
  ShowReadingTime: true
#  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
#  disableSpecial1stPost: false
  disableScrollToTop: false
#  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    text: "Sayfullah Sayeb"
#    icon: /apple-touch-icon.png
#   iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags


  homeInfoParams:
    Title: "Hi, I'm Sayfullah Sayeb 👋"
    Content: |
      Welcome to my portfolio! I am a passionate developer focused on creating impactful solutions.


      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. 

      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. 

      - 💻 Full Stack Developer
      - 🌟 Open Source Enthusiast
      - 📚 Continuous Learner

      Currently working on exciting projects and learning new technologies. 
      
      You can find my projects on GitHub and connect with me on LinkedIn.

  socialIcons:
    - name: cv
      url: "https://example.com"
    - name: github
      url: "https://github.com/mdsayeb7"
    - name: linkedin
      url: "https://www.linkedin.com/in/sayfullahsayeb/"
    - name: email
      url: "mailto:sayfullah.sayeb@gmail.com"
    - name: telegram
      url: "https://t.me/SayebPD"

#  analytics:
#    google:
#      SiteVerificationTag: ""
#    bing:
#      SiteVerificationTag: ""
#    yandex:
#      SiteVerificationTag: ""

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

#  editPost:
#    URL: "https://github.com/<path_to_repo>/content"
#    Text: "Suggest Changes" # edit text
#    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - name: Main Page
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 5
    - name: Posts
      url: /posts/
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 15
    - identifier: photography
      name: Photography
      url: /photography/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 25

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
#languages:
#  en:
#    languageName: "English"
#    weight: 1
#  bn:
#    languageName: "বাংলা"
#    weight: 2
